print("Hello world class5")

car: str = 'subaru'
print("\nIs car.lower() == 'subaru'? I predict True.")
print(car.lower() == 'subaru')
print("\nIs car.uper() == 'audi'? I predict False.")
print(car.upper() == 'subaru')
print("\nIs 1 == 1? I predict True.")
print(1 == 1)
print("\nIs 1 != 1? I predict False.")
print(1 != 1)
print("\nIs 5 > 4? I predict True.")
print(5 > 4)
print("\nIs 5 < 4? I predict False.")
print(5 < 4)
print("\nIs 5 >= 6? I predict False.")
print(5 >= 6)
print("\nIs 5 <= 6? I predict True.")
print(5 <= 6)
print("\nIs 5 == 5 and 5 != 6? I predict True.")
print(5 == 5 and 5 != 6)
names: list[str] = ["Hijabie", "gossipie", "Alizay"]
name: str = input("Enter a name: ")
name2: str = input("Enter a name: ")
print(f"Is {name} in names? I predict {name in names}")
print(f"Is {name2} in names? I predict {name2 in names}")

car2: str = 'subaru'
print("Is car == 'subaru'? I predict True.")
print(car2 == 'subaru')
print("\nIs car == 'audi'? I predict False.")
print(car2 == 'audi')
print("\nIs car != 'audi'? I predict True.")
print(car2 != 'audi')
print("\nIs car != 'subaru'? I predict False.")
print(car2 != 'subaru')
print("\nIs car == 'subaru' and car != 'audi'? I predict True.")
print(car2 == 'subaru' and car2 != 'audi')
print("\nIs car == 'subaru' or car == 'audi'? I predict True.")
print(car2 == 'subaru' or car2 == 'audi')
print("\nIs car == 'subaru' and car == 'audi'? I predict False.")
print(car2 == 'subaru' and car2 == 'audi')
print("\nIs car == 'audi' or car != 'audi'? I predict True.")
print(car2 == 'audi' or car2 != 'audi')
print("\nIs car == 'subaru' and car != 'subaru'? I predict False.")
print(car2 == 'subaru' and car2 != 'subaru')